name: planets_app
description: "Planets app for technical test"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Graphics
  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0
  animate_do: ^3.3.4
  
  # Riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Packages
  intl: ^0.19.0
  intl_utils: ^2.8.7
  logger: ^2.4.0
  go_router: ^14.2.8
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  envied: ^0.5.4+1
  either_dart: ^1.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

  # Generators
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: IntlTranslations
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/gen

flutter_gen:
  output: lib/gen